### ISSUE TITLE
Roadmap: v3.x.x

### ISSUE THREAD

**Issue by ijsKoud** [ijsKoud/PaperPlane#125]
## Roadmap: v3.0.0
This is the roadmap for **version 3.0.0**. Every item added to this list will be part of this update. 

#### Requested feature not on the list? 
Check the lists below or open an issue!

<details>
<summary><h2>To do list</h2></summary>

- [x] General
  - [x] Docker Support
    - [x] #79
  - [x] Updated guides
  - [x] Updated security policy
- [x] Back-end
  - [x] Server
  - [x] Password protected files
  - [x] Upload route
  - [x] Get route
  - [x] zerowidth ids
  - [x] user creation
  - [x] logging
  - [x] stats
  - [x] request logging
  - [x] api
    - [x] login
    - [x] update
    - [x] file search
    - [x] url search
- [x] Front-end
  - [x] App
  - [x] Pages
    - [x] #80
    - [x] Dashboard
    - [x] Login
    - [x] Settings
    - [x] Discord: image page
    - [x] User: password protected file page
    - [x] User: visibility on image & url
  - [x] Modals
    - [x] Upload
    - [x] URL create
  - [x] Components
  - [x] Notifications

</details>

**Comment by ijsKoud** [comment]
v3.1.0 refactor:
- [ ] use websockets in favour of re-fetching data
-> makes it easier to show up-to-date data and doesn't require passing through functions that refetches the data

**Comment by ijsKoud** [comment]
## Roadmap: v3.x.x
This is the roadmap for **version 3.x.x**. Every item added to this list will be part of this update. 

#### Requested feature not on the list? 
Check the lists below or open an issue!

<details>
<summary><h2>To do list</h2></summary>

- [ ] feat: data export function
-> Makes it easier for people to export and import data from one PaperPlane CDN to another, for example when moving servers or when migration from version x.y.z to version a.b.c

</details>
